org: pinx0
app: gptgram
service: gptgram
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: eu-west-3
  apiName: gptgram-api
  stage: prod
  environment:
    DATABASE_URL: ${param:database_url}
    SHADOW_DATABASE_URL: ${param:shadow_database_url}
    TORRENTE_BOT: ${param:torrente_bot}
    SIGMUND_BOT: ${param:sigmund_bot}
    ALFRED_BOT: ${param:alfred_bot}
    BOTIJIN_BOT: ${param:botijin_bot}

package:
  patterns:
    - "schema.prisma"
    - "libquery_engine-rhel-*"

functions:
  processMessage:
    handler: handler.processMessage
    memorySize: 256
    timeout: 25
    events:
      - httpApi:
          method: POST
          path: /gptgram/message

plugins:
  - serverless-esbuild
